/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 10
#define ALIAS_COUNT 0
#define TOKEN_COUNT 6
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_short_id = 2,
  sym_state = 3,
  sym_priority = 4,
  sym_title = 5,
  sym_source_file = 6,
  sym_task = 7,
  sym_lhs = 8,
  aux_sym_source_file_repeat1 = 9,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_short_id] = "short_id",
  [sym_state] = "state",
  [sym_priority] = "priority",
  [sym_title] = "title",
  [sym_source_file] = "source_file",
  [sym_task] = "task",
  [sym_lhs] = "lhs",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_short_id] = sym_short_id,
  [sym_state] = sym_state,
  [sym_priority] = sym_priority,
  [sym_title] = sym_title,
  [sym_source_file] = sym_source_file,
  [sym_task] = sym_task,
  [sym_lhs] = sym_lhs,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_short_id] = {
    .visible = true,
    .named = true,
  },
  [sym_state] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_lhs] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(sym_title);
      if (eof) ADVANCE(1);
      ADVANCE_MAP(
        '\n', 2,
        '(', 9,
        '/', 10,
        '\t', 6,
        ' ', 6,
        '-', 4,
        '.', 4,
        '?', 4,
        'x', 4,
        '~', 4,
      );
      if (lookahead != 0 &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_short_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_state);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_priority);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_title);
      ADVANCE_MAP(
        '\n', 2,
        '(', 9,
        '/', 10,
        '\t', 6,
        ' ', 6,
        '-', 4,
        '.', 4,
        '?', 4,
        'x', 4,
        '~', 4,
      );
      if (lookahead != 0 &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_title);
      ADVANCE_MAP(
        '(', 9,
        '/', 10,
        '\t', 7,
        ' ', 7,
        '-', 4,
        '.', 4,
        '?', 4,
        'x', 4,
        '~', 4,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_title);
      if (lookahead == ')') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_title);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_title);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_title);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_title);
      if (eof) ADVANCE(1);
      ADVANCE_MAP(
        '(', 9,
        '/', 10,
        '\t', 7,
        ' ', 7,
        '-', 4,
        '.', 4,
        '?', 4,
        'x', 4,
        '~', 4,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_short_id] = ACTIONS(1),
    [sym_state] = ACTIONS(1),
    [sym_priority] = ACTIONS(1),
    [sym_title] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym_task] = STATE(8),
    [sym_lhs] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_short_id] = ACTIONS(5),
    [sym_state] = ACTIONS(7),
    [sym_priority] = ACTIONS(9),
    [sym_title] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_task] = STATE(8),
    [sym_lhs] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_short_id] = ACTIONS(5),
    [sym_state] = ACTIONS(7),
    [sym_priority] = ACTIONS(9),
    [sym_title] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_task] = STATE(8),
    [sym_lhs] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_short_id] = ACTIONS(17),
    [sym_state] = ACTIONS(20),
    [sym_priority] = ACTIONS(23),
    [sym_title] = ACTIONS(26),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(31),
    [sym_short_id] = ACTIONS(31),
    [sym_state] = ACTIONS(33),
    [sym_priority] = ACTIONS(36),
    [sym_title] = ACTIONS(31),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(31),
    [sym_short_id] = ACTIONS(31),
    [sym_state] = ACTIONS(31),
    [sym_priority] = ACTIONS(36),
    [sym_title] = ACTIONS(31),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(31),
    [sym_short_id] = ACTIONS(31),
    [sym_state] = ACTIONS(31),
    [sym_priority] = ACTIONS(31),
    [sym_title] = ACTIONS(31),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(39),
    [anon_sym_LF] = ACTIONS(41),
    [sym_short_id] = ACTIONS(41),
    [sym_state] = ACTIONS(41),
    [sym_priority] = ACTIONS(41),
    [sym_title] = ACTIONS(41),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_LF] = ACTIONS(45),
    [sym_short_id] = ACTIONS(47),
    [sym_state] = ACTIONS(47),
    [sym_priority] = ACTIONS(47),
    [sym_title] = ACTIONS(47),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(39),
    [anon_sym_LF] = ACTIONS(41),
    [sym_short_id] = ACTIONS(41),
    [sym_state] = ACTIONS(41),
    [sym_priority] = ACTIONS(41),
    [sym_title] = ACTIONS(49),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [anon_sym_LF] = ACTIONS(53),
    [sym_short_id] = ACTIONS(53),
    [sym_state] = ACTIONS(53),
    [sym_priority] = ACTIONS(55),
    [sym_title] = ACTIONS(53),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [anon_sym_LF] = ACTIONS(53),
    [sym_short_id] = ACTIONS(53),
    [sym_state] = ACTIONS(53),
    [sym_priority] = ACTIONS(53),
    [sym_title] = ACTIONS(53),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(58),
    [anon_sym_LF] = ACTIONS(60),
    [sym_short_id] = ACTIONS(60),
    [sym_state] = ACTIONS(60),
    [sym_priority] = ACTIONS(60),
    [sym_title] = ACTIONS(60),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(62),
    [anon_sym_LF] = ACTIONS(64),
    [sym_short_id] = ACTIONS(64),
    [sym_state] = ACTIONS(64),
    [sym_priority] = ACTIONS(64),
    [sym_title] = ACTIONS(64),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 4,
      sym_short_id,
      sym_state,
      sym_priority,
      sym_title,
  [10] = 1,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 10,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lhs, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lhs, 1, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_lhs, 1, 0, 0), SHIFT(10),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_lhs, 1, 0, 0), SHIFT(11),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lhs, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lhs, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_lhs, 2, 0, 0), SHIFT(13),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lhs, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lhs, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rafta_nvim(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rafta_nvim",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
