name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    env:
      XDG_DATA_HOME: /tmp/xdg_data_home
      HOST_XDG_DATA_HOME: /tmp/xdg_data_home
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rev: [nightly, stable]
        include:
          - os: ubuntu-latest
            install-deps: sudo apt-get update && sudo apt-get install -y ripgrep && sudo apt-get install -y nodejs npm && npm install -g tree-sitter-cli
          - os: macos-latest
            install-deps: brew update && brew install ripgrep && brew install node && npm install -g tree-sitter-cli
          - os: windows-latest
            install-deps: choco install ripgrep && choco install nodejs && npm install -g tree-sitter-cli

    steps:
      - uses: actions/checkout@v5

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Prepare
        run: |
          ${{ matrix.install-deps }}
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ../nvim-treesitter
          git -C ../plenary.nvim fetch --unshallow
          git -C ../nvim-treesitter fetch --unshallow

      - name: Run tests
        run: |
          nvim --version
          make test
